version: "3.8"

services:

  airline-app:
    build: .
    container_name: airline-app
    ports:
      - "8080:8080"

  # Future database configuration
  # postgres:
  #   image: postgres:15
  #   container_name: airline-postgres
  #   environment:
  #     POSTGRES_DB: airline
  #     POSTGRES_USER: airline
  #     POSTGRES_PASSWORD: airline
  #   ports:
  #     - "5432:5432"
